service: serverless-message

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  apiKeys:
    - name: firstKeyMessageTelegram
      value: 9KJSDHSBHABHS78OFGJJHHJJKKL877
  environment:
    TELEGRAM_API_KEY: Your API Key
    TELEGRAM_CHAT_ID: Your chat ID
  usagePlan:
    quota:
      limit: 5000
      offset: 2
      period: MONTH
    throttle:
      burstLimit: 20
      rateLimit: 10

functions:
  sendMessage:
    handler: handler.sendMessage
    events:
      - http:
          path: send-message
          method: post
          cors: true
          private: true

plugins:
  - serverless-offline
